name = "DFTPostProcessing"
uuid = "c44b31a1-9253-442e-8d53-51009d9af719"
authors = ["YaozhenghangMa <Yaozhenghang.Ma@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
